application: track-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: profile.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
