application: track-bot
version: 1
runtime: python27
threadsafe: true
api_version: 1
handlers:
- url: /js
  static_dir: js
- url: /foo/.*
  script: main.foo_app
- url: .*
  script: main.app
libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
inbound_services:
- channel_presence